//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBackend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kustannuspaikat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kustannuspaikat()
        {
            this.Departments = new HashSet<Departments>();
        }
    
        public int Kustannuspaikka_id { get; set; }
        public string Nimi { get; set; }
        public Nullable<int> Contractor_id { get; set; }
        public Nullable<int> Department_id { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departments> Departments { get; set; }
    }
}
