//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileBackend.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheets
    {
        public int TimeSheet_id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public Nullable<int> Contractor_id { get; set; }
        public Nullable<int> Employee_id { get; set; }
        public Nullable<int> WorkAssignment_id { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> WorkComplete { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> LastModifiedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TimeDuration { get; set; }
    
        public virtual Contractors Contractors { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual WorkAssignments WorkAssignments { get; set; }
    }
}
